extra:
  version:
    provider: mike

site_name: Системы автоматизированного документооборота

site_description: Лекции по дисциплине САД

site_author: MKDocs Team


nav:
  - Главная: index.md
  - Лекция 1: lecture01.md
  - Лекция 2: lecture02.md
  - Лекция 3: lecture03.md
  - Лекция 4: lecture04.md
  - Лекция 5: lecture05.md

theme:
  name: 'material'
  repo-url: https://github.com/alineitgirl/EDMS
  features: 
    - navigation.expand
    - search.highlight
    - search.suggest
